`routes.txt`を作成済みであることが条件

# 便数を取得

In [40]:
import numpy as np
import pandas as pd
import collections
from pprint import pprint
import re
from IPython.core.display import display
import math

In [41]:
weekday_master_timetable = pd.read_excel('../rawdata/weekday.xls', sheet_name=None, header=None)
weekend_master_timetable = pd.read_excel('../rawdata/weekend.xls', sheet_name=None, header=None)

In [43]:
routes = pd.read_csv('../gtfs/routes.txt', index_col='route_id')
print('# 先頭')
display(routes.head(3))
print('# 末尾')
display(routes.tail(3))

# 先頭

,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,jp_parent_route_id
route_id,,,,,,,,,
100100,1430001056880,3,フェリー・工大・ろう学校線 (室蘭フェリーターミナル〜中島入口〜工大),NaN,3,NaN,NaN,NaN,NaN
100110,1430001056880,3,フェリー・工大・ろう学校線 (工大〜中島入口〜室蘭フェリーターミナル),NaN,3,NaN,NaN,NaN,NaN
100310,1430001056880,4,フェリー・工大・ろう学校線 (工大〜鷲別〜室蘭フェリーターミナル),NaN,3,NaN,NaN,NaN,NaN

# 末尾

,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,jp_parent_route_id
route_id,,,,,,,,,
130410,1430001056880,循2,中央町工大循環線 (工大〜中島入口〜中央町),NaN,3,NaN,NaN,NaN,NaN
107500,1430001056880,36,中島町資料館線 (中島入口〜東室蘭駅西口〜資料館前),NaN,3,NaN,NaN,NaN,NaN
107510,1430001056880,36,中島町資料館線 (資料館前〜東室蘭駅西口〜中島入口),NaN,3,NaN,NaN,NaN,NaN

In [44]:
weekdayTripNum = dict()
for i in weekday_master_timetable.keys():
    j = weekday_master_timetable[i].iat[0, 1]
    if not isinstance(j, float) or not math.isnan(j):
        m = re.search(r'便数:([\d]+)', j)
        if m:
            weekdayTripNum[i] = int(m.group(1))
        else:
            print('Error:', j)

In [48]:
weekdayTripNum

{'100310': 1,
 '100700': 1,
 '100710': 2,
 '101110': 1,
 '101500': 4,
 '101510': 4,
 '102300': 1,
 '104100': 1,
 '104110': 1,
 '104300': 13,
 '104310': 11,
 '106700': 9,
 '106810': 8,
 '106900': 12,
 '106910': 12,
 '107000': 2,
 '107010': 2,
 '107100': 10,
 '107110': 8,
 '107200': 2,
 '107210': 2,
 '107500': 2,
 '107510': 3,
 '107600': 6,
 '107610': 5,
 '107700': 3,
 '107710': 2,
 '107810': 1,
 '108500': 2,
 '108510': 1,
 '108700': 10,
 '108710': 10,
 '108800': 4,
 '108810': 5,
 '109000': 4,
 '109010': 3,
 '109100': 5,
 '109110': 5,
 '109200': 6,
 '109210': 5,
 '109220': 1,
 '110100': 14,
 '110110': 12,
 '110200': 13,
 '110210': 15,
 '110300': 3,
 '110310': 3,
 '112110': 1,
 '113700': 3,
 '113710': 5,
 '119010': 2,
 '120000': 2,
 '120200': 2,
 '120400': 1,
 '120800': 1,
 '120900': 1,
 '121000': 1,
 '123800': 1,
 '123810': 4,
 '124210': 1,
 '124400': 3,
 '126710': 1,
 '127100': 1,
 '127200': 1,
 '130100': 10,
 '130110': 11,
 '130200': 1,
 '130300': 2,
 '130310': 2,
 '130410': 1,
 '130500': 1,
 '130510': 1,
 '130600': 3,
 '130610': 3,
 '130700': 1,
 '130710': 1,
 '130800': 1,
 '130810': 1,
 '130900': 11,
 '131100': 9,
 '131110': 12,
 '131500': 1,
 '131610': 1,
 '131700': 1,
 '132200': 14,
 '132210': 15,
 '132610': 1,
 '150100': 1,
 '150110': 1,
 '150300': 1,
 '150310': 1,
 '150400': 1,
 '150410': 1,
 '150500': 1,
 '150510': 1,
 '150700': 1,
 '150710': 1,
 '150900': 1,
 '150910': 1,
 '151100': 1,
 '151110': 1,
 '200100': 1,
 '200110': 2,
 '200600': 9,
 '200610': 8,
 '210700': 1,
 '210710': 1,
 '220100': 5,
 '220110': 5,
 '230100': 2,
 '230110': 2,
 '230200': 4,
 '230210': 3,
 '240100': 5,
 '240110': 6,
 '250100': 13,
 '250110': 13,
 '250210': 1,
 '250310': 1,
 '250400': 6,
 '250410': 4,
 '270100': 4,
 '270110': 6,
 '270200': 3,
 '270210': 3,
 '270300': 8,
 '270310': 6,
 '290200': 5,
 '290210': 6,
 '290300': 2,
 '290310': 1,
 '290400': 1,
 '290410': 1,
 '300100': 7,
 '300110': 6,
 '300120': 2,
 '300130': 3,
 '311200': 1,
 '311210': 2,
 '311220': 6,
 '311230': 5,
 '311400': 2,
 '311410': 2,
 '312000': 3,
 '312010': 3,
 '312020': 1,
 '312030': 1,
 '312200': 1,
 '312210': 1,
 '320100': 4,
 '320110': 4,
 '320200': 5,
 '320210': 5,
 '330100': 2,
 '330110': 2,
 '330200': 3,
 '330210': 3,
 '330300': 1,
 '330310': 2,
 '330400': 1,
 '330410': 1,
 '330700': 1,
 '330710': 1,
 '340000': 1,
 '340210': 1,
 '350500': 1,
 '350510': 1,
 '350520': 3,
 '350530': 2,
 '360100': 2,
 '360110': 1,
 '360400': 1,
 '360710': 1,
 '360910': 1,
 '361000': 1,
 '361010': 1,
 '370500': 1,
 '370510': 1,
 '410500': 7,
 '410510': 7,
 '411500': 1,
 '411510': 1,
 '420000': 1,
 '420010': 3,
 '430100': 3,
 '430500': 1,
 '450100': 5,
 '450110': 4,
 '450310': 1,
 '450500': 2,
 '450600': 3,
 '450610': 4,
 '450700': 2,
 '450710': 1,
 '500500': 1,
 '500510': 1,
 '502500': 5,
 '502510': 5,
 '502700': 1,
 '502710': 1,
 '510600': 2,
 '510610': 2,
 '510800': 3,
 '510810': 3,
 '511600': 1,
 '513200': 1,
 '513210': 3,
 '513400': 1,
 '514410': 1,
 '515500': 1,
 '515700': 1,
 '515910': 1,
 '516500': 1,
 '517300': 1,
 '520100': 6,
 '520110': 7,
 '520200': 4,
 '520210': 4,
 '520300': 13,
 '520310': 13,
 '520400': 1,
 '520500': 1,
 '520510': 1,
 '520700': 1,
 '520710': 2,
 '521000': 1,
 '521010': 1,
 '521100': 3,
 '521110': 3,
 '521200': 1,
 '521210': 1,
 '532200': 1,
 '532210': 1,
 '550200': 5,
 '550210': 6,
 '560300': 1,
 '560310': 3,
 '592900': 1,
 '592910': 1,
 '600500': 3,
 '600510': 3,
 '600600': 1,
 '600910': 1,
 '620100': 2,
 '620110': 2,
 '620500': 2,
 '620510': 2,
 '660900': 4,
 '660910': 4,
 '670100': 3,
 '670110': 3,
 '670200': 3,
 '670300': 2,
 '670310': 2,
 '670510': 1,
 '680100': 2,
 '680110': 3,
 '700100': 4,
 '700110': 2,
 '720100': 7,
 '720110': 6,
 '790100': 1,
 '790110': 1,
 '800110': 19,
 '800120': 2,
 '800130': 1,
 '800140': 2,
 '800150': 2,
 '800210': 11,
 '800220': 6,
 '800230': 2,
 '800310': 15,
 '800320': 19,
 '800340': 4,
 '800350': 4,
 '800380': 10,
 '800390': 9,
 '801010': 4,
 '801020': 3,
 '801110': 19,
 '801120': 19,
 '801210': 15,
 '801220': 16,
 '801310': 14,
 '801320': 14,
 '801410': 3,
 '801420': 2,
 '801510': 10,
 '801520': 2,
 '801530': 5,
 '801540': 2,
 '801610': 13,
 '801620': 10,
 '801710': 11,
 '801720': 14,
 '801810': 7,
 '801910': 2,
 '801920': 2,
 '802110': 2,
 '802120': 4,
 '802130': 2,
 '802140': 3,
 '802210': 5,
 '802220': 5,
 '802410': 4,
 '802420': 5,
 '802510': 1,
 '802520': 1,
 '802530': 1,
 '802540': 9,
 '802550': 3,
 '802560': 1,
 '802610': 7,
 '802620': 4,
 '802630': 1,
 '802640': 1,
 '803110': 2,
 '803120': 2,
 '804150': 1,
 '804160': 1,
 '805320': 1,
 '805510': 1,
 '805520': 1,
 '805610': 1,
 '806010': 1,
 '806020': 1,
 '806110': 1,
 '806120': 1,
 '806130': 1,
 '806140': 1,
 '806150': 1,
 '806160': 1,
 '806210': 1,
 '806310': 1,
 '806410': 1,
 '806710': 1,
 '806910': 1,
 '807010': 1,
 '884100': 1,
 '884110': 1,
 '884120': 2,
 '884130': 2,
 '884140': 1,
 '894900': 1,
 '950100': 8,
 '950110': 9,
 '950900': 3,
 '950910': 3,
 '951100': 5,
 '951110': 5,
 '961510': 1,
 '964900': 2,
 '965100': 3,
 '965410': 1,
 '965610': 1,
 '965810': 2,
 '990100': 1,
 '990210': 1,
 '990510': 1,
 '990710': 1,
 '990900': 1,
 '990910': 1,
 '7700100': 6,
 '7700110': 7,
 '8100010': 7,
 '8100020': 7,
 '8100110': 1,
 '8100120': 1,
 '8101010': 10,
 '8101020': 9,
 '8101210': 5,
 '8101220': 4,
 '9000110': 3,
 '9000120': 1}

In [45]:
weekendTripNum = dict()
for i in weekend_master_timetable.keys():
    j = weekend_master_timetable[i].iat[0, 1]
    if not isinstance(j, float) or not math.isnan(j):
        m = re.search(r'便数:([\d]+)', j)
        if m:
            weekendTripNum[i] = int(m.group(1))
        else:
            print('Error:', j)

In [47]:
weekendTripNum

{'100310': 1,
 '100710': 2,
 '101110': 1,
 '101500': 3,
 '101510': 4,
 '104100': 1,
 '104300': 11,
 '104310': 10,
 '106700': 11,
 '106810': 9,
 '106900': 12,
 '106910': 12,
 '107100': 12,
 '107110': 11,
 '107600': 4,
 '107610': 3,
 '107700': 2,
 '107710': 2,
 '108500': 2,
 '108510': 2,
 '108700': 5,
 '108710': 7,
 '108800': 4,
 '108810': 4,
 '109000': 3,
 '109010': 3,
 '109100': 4,
 '109110': 3,
 '109200': 4,
 '109210': 4,
 '110100': 11,
 '110110': 11,
 '110200': 12,
 '110210': 13,
 '110300': 2,
 '110310': 2,
 '112110': 1,
 '113700': 4,
 '113710': 3,
 '119010': 1,
 '120000': 1,
 '120200': 1,
 '130100': 8,
 '130110': 10,
 '130200': 1,
 '130210': 1,
 '130300': 2,
 '130310': 2,
 '130500': 1,
 '130510': 1,
 '130600': 3,
 '130610': 3,
 '130700': 1,
 '130710': 1,
 '130800': 1,
 '130810': 1,
 '130900': 11,
 '131100': 9,
 '131110': 11,
 '131700': 1,
 '132200': 12,
 '132210': 12,
 '132610': 1,
 '150400': 1,
 '150410': 1,
 '150500': 1,
 '150510': 1,
 '150700': 1,
 '150710': 1,
 '150900': 1,
 '150910': 1,
 '151110': 1,
 '200100': 1,
 '200110': 2,
 '200600': 9,
 '200610': 8,
 '210700': 1,
 '210710': 1,
 '220100': 5,
 '220110': 5,
 '230100': 2,
 '230110': 2,
 '230200': 4,
 '230210': 3,
 '240100': 5,
 '240110': 6,
 '250100': 13,
 '250110': 13,
 '250210': 1,
 '250310': 1,
 '250400': 6,
 '250410': 4,
 '270100': 4,
 '270110': 6,
 '270200': 2,
 '270210': 2,
 '270300': 8,
 '270310': 6,
 '290200': 5,
 '290210': 6,
 '290300': 2,
 '290310': 1,
 '290400': 1,
 '290410': 1,
 '300100': 7,
 '300110': 6,
 '300120': 2,
 '300130': 3,
 '311200': 1,
 '311210': 2,
 '311220': 6,
 '311230': 5,
 '311400': 2,
 '311410': 2,
 '312000': 3,
 '312010': 3,
 '312020': 1,
 '312030': 1,
 '312200': 1,
 '312210': 1,
 '320100': 4,
 '320110': 4,
 '320200': 5,
 '320210': 5,
 '330100': 2,
 '330110': 2,
 '330200': 3,
 '330210': 3,
 '330300': 1,
 '330310': 2,
 '330400': 1,
 '330410': 1,
 '330700': 1,
 '330710': 1,
 '340000': 1,
 '340210': 1,
 '350500': 1,
 '350510': 1,
 '350520': 3,
 '350530': 2,
 '360100': 2,
 '360110': 1,
 '360400': 1,
 '360710': 1,
 '360910': 1,
 '361000': 1,
 '361010': 1,
 '370500': 1,
 '370510': 1,
 '410500': 7,
 '410510': 7,
 '411500': 1,
 '411510': 1,
 '420000': 1,
 '430100': 3,
 '430500': 1,
 '450100': 5,
 '450110': 4,
 '450310': 1,
 '450500': 2,
 '450600': 3,
 '450610': 4,
 '450700': 2,
 '450710': 1,
 '500500': 1,
 '500510': 1,
 '502500': 5,
 '502510': 5,
 '502700': 1,
 '502710': 1,
 '510600': 2,
 '510610': 2,
 '510800': 3,
 '510810': 3,
 '511600': 1,
 '513200': 1,
 '513210': 1,
 '514410': 1,
 '515700': 1,
 '515910': 1,
 '516500': 1,
 '517300': 1,
 '520100': 6,
 '520110': 7,
 '520200': 4,
 '520210': 4,
 '520300': 13,
 '520310': 13,
 '520400': 1,
 '520500': 1,
 '520510': 1,
 '520700': 1,
 '520710': 2,
 '521000': 1,
 '521010': 1,
 '521100': 3,
 '521110': 3,
 '521200': 1,
 '521210': 1,
 '532200': 1,
 '532210': 1,
 '550200': 5,
 '550210': 6,
 '592900': 1,
 '592910': 1,
 '600500': 3,
 '600510': 3,
 '600600': 1,
 '600910': 1,
 '620100': 2,
 '620110': 2,
 '620500': 2,
 '620510': 2,
 '660900': 4,
 '660910': 4,
 '670100': 3,
 '670110': 3,
 '670200': 3,
 '670300': 2,
 '670310': 2,
 '670510': 1,
 '680100': 1,
 '700100': 4,
 '700110': 2,
 '720100': 7,
 '720110': 6,
 '790100': 1,
 '790110': 1,
 '800110': 21,
 '800120': 2,
 '800210': 6,
 '800220': 6,
 '800230': 2,
 '800310': 12,
 '800320': 13,
 '800340': 4,
 '800350': 4,
 '800380': 6,
 '800390': 5,
 '801110': 17,
 '801120': 15,
 '801210': 13,
 '801220': 13,
 '801310': 11,
 '801320': 12,
 '801510': 8,
 '801520': 1,
 '801530': 4,
 '801540': 2,
 '801610': 11,
 '801620': 11,
 '801710': 10,
 '801720': 9,
 '801810': 3,
 '802110': 1,
 '802120': 1,
 '802130': 2,
 '802140': 2,
 '802210': 5,
 '802220': 5,
 '802410': 4,
 '802420': 5,
 '802510': 1,
 '802540': 7,
 '802550': 2,
 '802570': 1,
 '802580': 1,
 '802610': 5,
 '802620': 2,
 '802630': 1,
 '802640': 4,
 '807150': 1,
 '807160': 1,
 '807250': 1,
 '807260': 1,
 '807350': 1,
 '807360': 1,
 '807450': 1,
 '807460': 1,
 '950100': 8,
 '950110': 9,
 '950900': 3,
 '950910': 3,
 '951100': 5,
 '951110': 5,
 '961510': 1,
 '964900': 2,
 '965100': 3,
 '965410': 1,
 '965610': 1,
 '965810': 2,
 '990100': 1,
 '990210': 1,
 '990710': 1,
 '990900': 1,
 '990910': 1,
 '7700100': 6,
 '7700110': 7,
 '8100010': 7,
 '8100020': 7,
 '8100110': 1,
 '8100120': 1,
 '8101010': 10,
 '8101020': 9,
 '8101210': 5,
 '8101220': 4}

# 過去のやつ

In [113]:
trips_2017 = pd.read_csv('../gtfs_201704/trips.txt', index_col=0)
trips_2017.head(3)

,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed,jp_trip_desc,jp_trip_desc_symbol,jp_office_id
route_id,,,,,,,,,,,,
100110,weekday,100110_weekday_1,NaN,NaN,0,NaN,6859990,0,0,NaN,NaN,NaN
100310,weekday,100310_weekday_1,NaN,NaN,0,NaN,6860091,0,0,NaN,NaN,NaN
100700,weekday,100700_weekday_1,NaN,NaN,1,NaN,6860195,0,0,NaN,NaN,NaN

# 記号付きを取得

In [54]:
weekday_master_timetable = pd.read_excel('../rawdata/weekday.xls', sheet_name=None, skiprows=2, index_col=1)
weekday_master_timetable = {i: weekday_master_timetable[i].dropna(how='all', axis=1) for i in weekday_master_timetable.keys()}
weekend_master_timetable = pd.read_excel('../rawdata/weekend.xls', sheet_name=None, skiprows=2, index_col=1)
weekend_master_timetable = {i: weekend_master_timetable[i].dropna(how='all', axis=1) for i in weekend_master_timetable.keys()}

In [168]:
def service_id(i, sd, d, s, num):
    direction_id = None
    if i == 130410:
        direction_id = trips_2017.at[130310, 'direction_id']
    elif i == 107500:
        direction_id = trips_2017.at[107600, 'direction_id']
    elif i == 107510:
        direction_id = trips_2017.at[107610, 'direction_id']
    else:
        direction_id = trips_2017.at[i, 'direction_id']
    if isinstance(direction_id, np.ndarray):
        direction_id = direction_id[0]
    if s == '':
        return pd.DataFrame(
            [[sd, f'{d}_{i}_{n}', None, None, direction_id, None, None, 0, 0, None, None, None] for n in range(num)],
            columns=['service_id', 'trip_id', 'trip_headsign', 'trip_short_name', 'direction_id', 'block_id', 'shape_id', 'wheelchair_accessible', 'bikes_allowed', 'jp_trip_desc', 'jp_trip_desc_symbol', 'jp_office_id'],
            index=pd.Int64Index([i for n in range(num)], name='route_id')
        )
    elif s == '●':
        return pd.DataFrame(
            [[sd, f'{d}_{i}_school_{n}', None, None, direction_id, None, None, 0, 0, None, None, None] for n in range(num)],
            columns=['service_id', 'trip_id', 'trip_headsign', 'trip_short_name', 'direction_id', 'block_id', 'shape_id', 'wheelchair_accessible', 'bikes_allowed', 'jp_trip_desc', 'jp_trip_desc_symbol', 'jp_office_id'],
            index=pd.Int64Index([i for n in range(num)], name='route_id')
        )

In [169]:
trips = pd.DataFrame()
sd = '20180401_weekday'
d = 'weekday'
for i in list(routes.index):
    s = list(map(lambda x: x.strip(), weekday_master_timetable[f'{i}'].loc['記号など'].values))
    if s != []:
#        print(i, end=' ')
#        print(s, end=' ')
        n = len(list(filter(lambda x: x == '', s)))
        ss = len(list(filter(lambda x: x == '●', s)))
#        print(n, end=', ')
#        print(ss, end=' ')
#        print(weekdayTripNum[f'{i}'] == n+ss)
#        print(service_id(i, sd, d, '', n))
#        print(service_id(i, sd, d, '●', ss))
        if n > 0:
            trips=trips.append(service_id(i, sd, d, '', n))
        if ss > 0:
            trips=trips.append(service_id(i, sd, d, '●', ss))
sd = '20180401_weekend'
d = 'weekend'
for i in list(routes.index):
    s = list(map(lambda x: x.strip(), weekend_master_timetable[f'{i}'].loc['記号など'].values))
    if s != []:
#        print(i, end=' ')
#        print(s, end=' ')
        n = len(list(filter(lambda x: x == '', s)))
        ss = len(list(filter(lambda x: x == '●', s)))
#        print(n, end=', ')
#        print(ss, end=' ')
#        print(weekendTripNum[f'{i}'] == n+ss)
#        print(service_id(i, sd, d, '', n))
#        print(service_id(i, sd, d, '●', ss))
        if n > 0:
            trips=trips.append(service_id(i, sd, d, '', n))
        if ss > 0:
            trips=trips.append(service_id(i, sd, d, '●', ss))

In [170]:
trips

,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed,jp_trip_desc,jp_trip_desc_symbol,jp_office_id
route_id,,,,,,,,,,,,
100310,20180401_weekday,weekday_100310_0,None,None,0,None,None,0,0,None,None,None
100700,20180401_weekday,weekday_100700_0,None,None,1,None,None,0,0,None,None,None
100710,20180401_weekday,weekday_100710_0,None,None,0,None,None,0,0,None,None,None
100710,20180401_weekday,weekday_100710_1,None,None,0,None,None,0,0,None,None,None
101110,20180401_weekday,weekday_101110_0,None,None,0,None,None,0,0,None,None,None
101500,20180401_weekday,weekday_101500_0,None,None,1,None,None,0,0,None,None,None
101500,20180401_weekday,weekday_101500_1,None,None,1,None,None,0,0,None,None,None
101500,20180401_weekday,weekday_101500_2,None,None,1,None,None,0,0,None,None,None
101500,20180401_weekday,weekday_101500_3,None,None,1,None,None,0,0,None,None,None
101510,20180401_weekday,weekday_101510_0,None,None,0,None,None,0,0,None,None,None
101510,20180401_weekday,weekday_101510_1,None,None,0,None,None,0,0,None,None,None
101510,20180401_weekday,weekday_101510_2,None,None,0,None,None,0,0,None,None,None
101510,20180401_weekday,weekday_101510_3,None,None,0,None,None,0,0,None,None,None
102300,20180401_weekday,weekday_102300_0,None,None,1,None,None,0,0,None,None,None
104100,20180401_weekday,weekday_104100_0,None,None,1,None,None,0,0,None,None,None
104110,20180401_weekday,weekday_104110_0,None,None,0,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_0,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_1,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_2,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_3,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_4,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_5,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_6,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_7,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_8,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_9,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_10,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_11,None,None,1,None,None,0,0,None,None,None
104300,20180401_weekday,weekday_104300_12,None,None,1,None,None,0,0,None,None,None
104310,20180401_weekday,weekday_104310_0,None,None,0,None,None,0,0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
131110,20180401_weekend,weekend_131110_7,None,None,0,None,None,0,0,None,None,None
131110,20180401_weekend,weekend_131110_8,None,None,0,None,None,0,0,None,None,None
131110,20180401_weekend,weekend_131110_9,None,None,0,None,None,0,0,None,None,None
131110,20180401_weekend,weekend_131110_10,None,None,0,None,None,0,0,None,None,None
131700,20180401_weekend,weekend_131700_0,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_0,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_1,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_2,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_3,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_4,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_5,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_6,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_7,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_8,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_9,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_10,None,None,1,None,None,0,0,None,None,None
132200,20180401_weekend,weekend_132200_11,None,None,1,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_0,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_1,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_2,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_3,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_4,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_5,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_6,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_7,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_8,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_9,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_10,None,None,0,None,None,0,0,None,None,None
132210,20180401_weekend,weekend_132210_11,None,None,0,None,None,0,0,None,None,None
132610,20180401_weekend,weekend_132610_0,None,None,0,None,None,0,0,None,None,None

In [171]:
trips.to_csv('../gtfs/trips.txt')